WIP: feat(canvas):Add multiple routes control
KaotoIO/kaoto-next pull request #209
Opened 2023-10-09 14:07 UTC by mmelko

2023-10-19 13:26 UTC, lordrip requested changes
Thanks for bringing this @mmelko.

There are a few rough edges that we might need to polish (please see the related comments)

In addition to that, there might be missing functionality for `KameletBinding` and `Pipe` because the list doesn't work with them.

Also, it looks like the counter needs a refresh, because after adding a new route in the source code editor, notice how the counter is bigger than expected.

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/3b2e21e1-d955-4129-a199-67c9f47e295f)

2023-10-19 13:26 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
> +
```suggestion
```

2023-10-19 13:26 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
> +              <p>{''}</p>
Maybe this is not necessary, as it shows on the UI
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/807b753c-cdad-42b9-ad6c-14ee7afa3513)



```suggestion
```

2023-10-19 13:26 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
> +                //  validator={ValidationService.validateUniqueName}
[curious-question] Can we bring this functionality over?

2023-10-19 13:26 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.test.tsx
> +describe('FlowTypeSelector.tsx', () => {
```suggestion

describe('FlowTypeSelector.tsx', () => {
```

2023-10-19 13:26 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.test.tsx
> +    const wrapper = renderWithContext();
[:nail_care:] What do you think about keeping this abstraction over rendering the component but as a custom component instead.

The usage would be:

```typescript
render(<FlowTypeSelectorWithContext />)
```

And the component would be:
```jsx
const FlowTypeSelectorWithContext: FunctionComponent = () => {
  return (
    <EntitiesContext.Provider value={contextValue as unknown as EntitiesContextResult}>
        <FlowTypeSelector onSelect={onSelect} />
    </EntitiesContext.Provider>
  );
};

2023-10-19 13:26 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
> +//jest.mock(visibleFlov)
```suggestion
```

2023-10-19 14:26 UTC, mmelko commented on packages/ui/src/models/camel/source-schema-config.ts
> +  getAsList(): ISourceSchema[] {
I was planning to use that but then I switch to using  SourceSchemaType IRRC. So I can delete this and use in the test `Object.values()`

2023-10-20 08:32 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.test.tsx
> +    const wrapper = renderWithContext();
Yes, mostly readability.

2023-10-20 11:14 UTC, mmelko commented on packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
> +      // minWidth="400px"
attribute doesn't exist anymore

2023-10-20 12:28 UTC, mmelko commented
@lordrip please check :)

2023-10-20 12:28 UTC, lordrip approved these changes

2023-10-20 12:32 UTC, merged