feat(viz): Implement `New Route` and `Remove` route
KaotoIO/kaoto-next pull request #254
Opened 2023-10-25 08:56 UTC by mmelko

Make `New Route` and Remove route functional. Also I refactored  VisibleFlowsReducer to be more readable and fixed wrong numbers. 
This PR also introduces flowTemplateService which in the future should be use to provide default yaml templates when adding new flows.

2023-10-25 09:59 UTC, lordrip requested changes
Overall LGTM, there are just a few open topics:

1. Showing 2 routes, you can only configure the steps from the second one. After testing kaotoio.github.io/kaoto-next, it seems this issue was already happening and is being tracked here: https://github.com/KaotoIO/kaoto-next/issues/255

2. Having 3 routes, seeing the third one, going back to the code, and returning to the canvas, then you start by seeing the first one again (probably this is due to the camel resource changing all the time)

3. It looks like we can't delete a `Pipe`, we need to create a Camel Route first and then go back, in order to reset it.

2023-10-25 09:59 UTC, lordrip commented on packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
> +      //  console.log('selected new flow', flowType);
```suggestion
```

2023-10-25 09:59 UTC, lordrip commented on packages/ui/src/hooks/entities.ts
> +      flowTemplateService: flowTemplateService,
```suggestion
      flowTemplateService,
```

2023-10-25 09:59 UTC, lordrip commented on packages/ui/src/providers/visible-flows.provider.tsx
> +    const hiddenAll = Object.values(flows).reduce((acc, current) => acc && !current, true);
```suggestion
    const hiddenAll = Object.values(flows).every((visible) => visible);
```

2023-10-25 09:59 UTC, lordrip commented on packages/ui/src/models/visualization/flows/flows-visibility.ts
> +  clearFlows() {
```suggestion

  clearFlows() {
```

2023-10-25 09:59 UTC, lordrip commented on packages/ui/src/models/visualization/flows/flows-visibility.ts
> +    this.dispatch({ type: 'toggleFlowVisible', flowId: flowId, isVisible: isVisible });
```suggestion
    this.dispatch({ type: 'toggleFlowVisible', flowId, isVisible });
```

2023-10-25 13:39 UTC, mmelko commented
to 3. I cannot reproduce this. For me the Pipe is being always deleted/(replaced) with the template. 
to 4. I've  modified route and tested with the jbang. And added defaults to the Pipe

2023-10-26 08:04 UTC, lordrip commented
After investigating the root cause of # 3, it seems that is an underlying issue of the `CamelKResource` class and how it works together with the `entities` hook.

**TL;DR**

1. The entities get returned just once, at the [creation of the Camel Resource here](https://github.com/KaotoIO/kaoto-next/blob/1f6d4e8ad4f3c3166dabc574c0c33de6ed1b251d/packages/ui/src/hooks/entities.ts#L64)

2. Notice that for CamelK, the entities [are being returned as an object](https://github.com/KaotoIO/kaoto-next/blob/1f6d4e8ad4f3c3166dabc574c0c33de6ed1b251d/packages/ui/src/models/camel/camel-k-resource.ts#L56-L60)

3. When we delete a flow from the list, we [set the code here](https://github.com/KaotoIO/kaoto-next/pull/254/files#diff-1b34d17fcee493bb7b1a3ef11a71c2488cf59a10e3f57bfcfdcc35904cf44b80R93-R94)

4. After that, we [stringify the Camel Resource here](https://github.com/KaotoIO/kaoto-next/blob/1f6d4e8ad4f3c3166dabc574c0c33de6ed1b251d/packages/ui/src/hooks/entities.ts#L44-L51), but at this point is still the previous Camel K resource, it hasn't changed, hence the UI gets stuck with the previous one forever and ever.

That being said, with your recent updates, I'll merge this pull request to avoid blocking the Camel Route functionality.

2023-10-26 08:07 UTC, lordrip approved these changes

2023-10-26 08:08 UTC, merged