fix(vscode): Fix VSCode switching integration type
KaotoIO/kaoto-next pull request #549
Opened 2023-12-12 13:19 UTC by lordrip

### Context
Currently, when VSCode switch from one integration type to another, for instance, going from a Camel Route to a Kamelet, this change is not persisted until a property is changed.

This happens because the `KaotoBridge` is not subscribed to the `code:updated` event and this is used when changing from one integration type to another.

### Changes
The fix is to subscribe to that envent. In addition to that, since [this PR](https://github.com/KaotoIO/kaoto-next/pull/541), the `VisibleFlowsProvider` was removed from the `Visualization` component, hence it was breaking the VSCode integration. This PR also adds it to the `KaotoBridge`

fixes: https://github.com/KaotoIO/kaoto-next/issues/402

2023-12-12 13:20 UTC, lordrip commented on packages/ui/src/multiplying-architecture/KaotoBridge.tsx
> +    const unsubscribeFromSourceCode = eventNotifier.subscribe('code:updated', (newContent: string) => {
Subscribing to `code:updated` event so when a new route is added, the new template update gets reflected on the `KaotoEditor` component

2023-12-12 13:23 UTC, lordrip commented on packages/ui/src/multiplying-architecture/KaotoBridge.tsx
> -  const sourceCodeContext = useContext(SourceCodeContext);
We can spare the `sourceCode` from the provider since we're starting with an empty string which later on gets updated by the file content.

2023-12-12 16:44 UTC, apupier requested changes
the file is saved with 2 extra spaces at beginning of each line and an empty new line at the beginning:

```

  apiVersion: camel.apache.org/v1
  kind: Pipe
  metadata:
    name: pipe-3703
  spec:
    source:
      ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: timer-source
        properties:
          message: hello
    sink:
      ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: log-sink
 ```

2023-12-13 09:03 UTC, lordrip commented
> the file is saved with 2 extra spaces at beginning of each line and an empty new line at the beginning:
> 
> ```
> 
>   apiVersion: camel.apache.org/v1
>   kind: Pipe
>   metadata:
>     name: pipe-3703
>   spec:
>     source:
>       ref:
>         kind: Kamelet
>         apiVersion: camel.apache.org/v1
>         name: timer-source
>         properties:
>           message: hello
>     sink:
>       ref:
>         kind: Kamelet
>         apiVersion: camel.apache.org/v1
>         name: log-sink
> ```

I see, it was the template wrongly formatted in `kaoto-next` side, I updated it.

2023-12-14 15:06 UTC, lhein approved these changes

2023-12-14 15:34 UTC, apupier approved these changes
cannot judge potential  impactvon other parts but checked in VS Code that it is now working fine

2023-12-15 13:38 UTC, merged