feat(sourcecode): Serialize URI string
KaotoIO/kaoto-next pull request #900
Opened 2024-03-04 16:50 UTC by lordrip

### Context
Currently, only the component name gets serialized into the URI string, the remaining parameters ar serialized in the parameters dictionary as follows:

```yaml
  - from:
      uri: timer
      parameters:
        period: "1000"
        timerName: template
```

While this works for the Camel CLI, CamelK doesn't support this schema at the moment, causing the deployment to fail.

This commit writes the path parameters into the URI string, in order to support CamelK deployments, f.i.:
```yaml
  - from:
      uri: timer:template
      parameters:
        period: "1000"
```

fixes: https://github.com/KaotoIO/kaoto-next/issues/884

2024-03-05 08:19 UTC, apupier requested changes
searching how to reproduce but ended with a lot of double-dot:

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/c5bdc77d-634e-4602-ad0b-96ebc04d64d0)

2024-03-05 08:24 UTC, apupier commented
![extraDoubleDotAdded](https://github.com/KaotoIO/kaoto-next/assets/1105127/f7114af5-d84b-4a03-978e-58400ccebbd9)

2024-03-05 08:34 UTC, lordrip commented
> ![extraDoubleDotAdded](https://private-user-images.githubusercontent.com/1105127/310037488-f7114af5-d84b-4a03-978e-58400ccebbd9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjc3NDAsIm5iZiI6MTcwOTYyNzQ0MCwicGF0aCI6Ii8xMTA1MTI3LzMxMDAzNzQ4OC1mNzExNGFmNS1kODRiLTRhMDMtOTc4ZS01ODQwMGNjZWJiZDkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDgzMDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRlOWQ4MTVjNGE3M2FiYzhiZGVmNzFmMWZkMDk1M2M3NWEwM2ZiZDIwNmFiZjVlYzhkNjYyMjNlYjMyMmYzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TRCLIyyEHcEXOn3-KlxCC0QoPJc8JzX3CDoQzXCcto4) [ ![extraDoubleDotAdded](https://private-user-images.githubusercontent.com/1105127/310037488-f7114af5-d84b-4a03-978e-58400ccebbd9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjc3NDAsIm5iZiI6MTcwOTYyNzQ0MCwicGF0aCI6Ii8xMTA1MTI3LzMxMDAzNzQ4OC1mNzExNGFmNS1kODRiLTRhMDMtOTc4ZS01ODQwMGNjZWJiZDkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDgzMDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRlOWQ4MTVjNGE3M2FiYzhiZGVmNzFmMWZkMDk1M2M3NWEwM2ZiZDIwNmFiZjVlYzhkNjYyMjNlYjMyMmYzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TRCLIyyEHcEXOn3-KlxCC0QoPJc8JzX3CDoQzXCcto4) ](https://private-user-images.githubusercontent.com/1105127/310037488-f7114af5-d84b-4a03-978e-58400ccebbd9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjc3NDAsIm5iZiI6MTcwOTYyNzQ0MCwicGF0aCI6Ii8xMTA1MTI3LzMxMDAzNzQ4OC1mNzExNGFmNS1kODRiLTRhMDMtOTc4ZS01ODQwMGNjZWJiZDkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDgzMDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRlOWQ4MTVjNGE3M2FiYzhiZGVmNzFmMWZkMDk1M2M3NWEwM2ZiZDIwNmFiZjVlYzhkNjYyMjNlYjMyMmYzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TRCLIyyEHcEXOn3-KlxCC0QoPJc8JzX3CDoQzXCcto4) [ ](https://private-user-images.githubusercontent.com/1105127/310037488-f7114af5-d84b-4a03-978e-58400ccebbd9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjc3NDAsIm5iZiI6MTcwOTYyNzQ0MCwicGF0aCI6Ii8xMTA1MTI3LzMxMDAzNzQ4OC1mNzExNGFmNS1kODRiLTRhMDMtOTc4ZS01ODQwMGNjZWJiZDkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDgzMDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRlOWQ4MTVjNGE3M2FiYzhiZGVmNzFmMWZkMDk1M2M3NWEwM2ZiZDIwNmFiZjVlYzhkNjYyMjNlYjMyMmYzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TRCLIyyEHcEXOn3-KlxCC0QoPJc8JzX3CDoQzXCcto4)

Awesome, thanks for catching it, I pushed a fix for a related issue

2024-03-05 08:52 UTC, apupier requested changes
for rest-openapi, the path parameters are still written as attributes:

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/07b9c3bc-44e4-49f5-ae8a-a479bc42172b)

```yaml
- route:
    id: route-4144
    from:
      id: from-1532
      uri: timer
      parameters:
        period: "1000"
        timerName: template
      steps:
        - log:
            id: log-3429
            message: template message
        - to:
            id: to-1027
            uri: rest-openapi
            parameters:
              operationId: myOperation
              specificationUri: afile-openapi.json
```

2024-03-05 09:02 UTC, apupier commented
The component can be modified:
![changingUriScheme](https://github.com/KaotoIO/kaoto-next/assets/1105127/00f3f084-3853-451a-8613-1645a9518671)

in source code, notice the `resta` instead of `rest`:
```yaml
- route:
    id: route-4144
    from:
      id: from-1532
      uri: timer
      parameters:
        period: "1000"
        timerName: template
      steps:
        - log:
            id: log-3429
            message: template message
        - to:
            id: to-2923
            uri: resta
            parameters:
              uriTemplate: atemplate
 ```

2024-03-05 09:06 UTC, apupier commented
surely related to previous one as it seems to be one-off shift but slightly different case:
![FirstLetterStoredInPreviousPathParameter](https://github.com/KaotoIO/kaoto-next/assets/1105127/95367603-c674-401c-8c53-4e09e97d827d)

2024-03-06 09:28 UTC, lordrip commented
> * reported issues fixed
> 
>     * not spotted new ones
> 
>     * seems all cases covered by automates test cases

Thanks for the @apupier, but now I think I spotted something else that I think it would be better to fix.

As an example, the `rest` component has the following syntax: `rest:method:path:uriTemplate`, and while `method` and `path` are required parameters, `urlTemplate` it is not.

At this moment, when serializing the URI, if the `urlTemplate` is not provided, we end up with the following `URI`:
```
uri: "rest:get:myPath:"
```

I think it's not ideal, as it would be preferable to ignore the last `:` when there's an optional parameter.

This will require a bit more love since we would need to check the upcoming parameters as well, considering that for multiple optional parameters, we could provide just the last one, in which case, we would need to serialize the entire URI up to the last parameter :scream_cat:

2024-03-06 13:24 UTC, lordrip commented
Af this update, the optional parameters are only written if the next value is either required or provided.

2024-03-06 14:42 UTC, apupier approved these changes

2024-03-06 15:10 UTC, merged